Some example rules to add
ambanum/CGUs pull request #113
Opened 2020-08-28 11:17 UTC by michielbdejong

In tosback2 we have for instance "Alexa Terms of Service" under amazon.com.xml.
I translated those to "Terms of Service" of "AmazonAlexa.json".

Here are a few examples of how my script creates them now. Note that they contain the selectors translated from xpath, but when creating the imported versions, i'm using 'body' as the selector.

2020-08-31 13:54 UTC, Ndpnt commented
Great!
Last week, with @MattiSG , we wrote a [first version of what could be documentation for common practice](https://github.com/ambanum/CGUs/issues/106#issuecomment-681870747) for choosing a service name. If you agree with it and you think it covers all the cases you might encounter, can you use it to name both the file and the service in the declaration?

2020-09-01 21:38 UTC, MattiSG commented
This looks good, taking into accounts @Ndpnt's comment on naming 👍

I see only Alexa for now while you use the plural in comments, is it expected or is there a glitch? 🙂

2020-09-02 12:30 UTC, michielbdejong commented
Ah yes sorry, instead of " Here are a few examples" I should have said "Here is one example" :)

2020-09-02 16:43 UTC, MattiSG commented
No worries, just wanted to make sure I had not missed something  :)

2020-09-02 16:44 UTC, MattiSG requested changes

2020-09-02 16:44 UTC, MattiSG commented on services/AmazonAlexa.json
> +  "name": "AmazonAlexa",
According to #106:

```suggestion
  "name": "Alexa",
```

Or, if ambiguous:

```suggestion
  "name": "Amazon Alexa",
```

2020-09-11 13:39 UTC, closed without merging