Add convenient gitdiff commands
ambanum/CGUs pull request #174
Opened 2020-10-14 13:35 UTC by LucasVerneyDGE

Hi,

When adding new services, it is convenient to be able to run in a single command the checks on the modified services. Here is a proposal for such a npm command. Let me know what you think about it and whether it might be of interest :)

Best,

2020-10-21 15:52 UTC, LucasVerneyDGE commented
Updated with this logic.

2020-10-28 08:50 UTC, Ndpnt requested changes
Hi @LucasVerneyDGE,
Thanks for this CLI improvement!
Just some minors changes and it's GTM for me.

2020-10-28 08:50 UTC, Ndpnt commented on src/index.js
> +  }
Can you add a new line after the `}`?

2020-10-28 08:50 UTC, Ndpnt commented on src/index.js
> +    return;
Add a log, something like `logger.warn('No services have been modified');`

2020-10-28 08:50 UTC, Ndpnt commented on src/tools/index.js
> +import path from 'path';
Rename `tools` in `utils`, it seems more idiomatic to me.

2020-10-28 08:50 UTC, Ndpnt commented on src/tools/index.js
> +export async function getModifiedServices(rootPath) {
As the path for `services` is always the same no matter where we call this function, I'm in favor of not passing `rootPath` as parameter but defining it directly inside this module.

2020-10-28 08:50 UTC, Ndpnt commented on src/index.js
> +  if (modifiedOnly) {
Add a newline before the `if` to create meaningful blocs

2020-10-28 08:50 UTC, Ndpnt commented
Also, can you please rebase master branch.

2020-10-28 09:50 UTC, LucasVerneyDGE commented
Thanks for the review, PR should be updated!

2020-10-29 08:17 UTC, MattiSG approved these changes
Not tested locally, but discussed & read. Thanks @LucasVerneyDGE!

As complexity in handling services increases, for example when implementing #156, it will be appropriate to move the `getModifiedServices` logic in a `services` or `documents` module,  rather than `utils` 🙂

2020-10-29 10:03 UTC, merged